//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public Auth()
        {
            this.Client1 = new HashSet<Client>();
            this.Doctor1 = new HashSet<Doctor>();
        }
    
        public int IDAuth { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IDRols { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDDoctor { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Rols Rols { get; set; }
        public virtual ICollection<Client> Client1 { get; set; }
        public virtual ICollection<Doctor> Doctor1 { get; set; }
    }
}
