//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public Auth()
        {
            this.Client = new HashSet<Client>();
            this.Doctor = new HashSet<Doctor>();
        }
    
        public int IDAuth { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IDRols { get; set; }
    
        public virtual Rols Rols { get; set; }
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}
