//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependece
    {
        public Dependece()
        {
            this.health = new HashSet<health>();
        }
    
        public int IDDependece { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<health> health { get; set; }
    }
}
