//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int IDDoctor { get; set; }
        public string FName { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string Pasport { get; set; }
        public string Polis { get; set; }
        public string SNILS { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public int IDDoctorCategory { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> IDAuth { get; set; }
        public string InfoDoctor { get; set; }
    
        public virtual Auth Auth { get; set; }
        public virtual DoctorCategory DoctorCategory { get; set; }
    }
}
