//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorCategory
    {
        public DoctorCategory()
        {
            this.Doctor = new HashSet<Doctor>();
        }
    
        public int IDDoctorCategory { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}
