//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReabilCenterEntities : DbContext
    {
        public ReabilCenterEntities()
            : base("name=ReabilCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auth> Auth { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Dependece> Dependece { get; set; }
        public DbSet<Doctor> Doctor { get; set; }
        public DbSet<DoctorCategory> DoctorCategory { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<health> health { get; set; }
        public DbSet<HistoryClient> HistoryClient { get; set; }
        public DbSet<Photo> Photo { get; set; }
        public DbSet<Rols> Rols { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Therapy> Therapy { get; set; }
    }
}
