//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation_Center.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapyHistory
    {
        public int IDTherapy { get; set; }
        public int IDClient { get; set; }
        public int ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Therapy Therapy { get; set; }
    }
}
